BEGIN;
--
-- Create model users_info
--
CREATE TABLE "AddUser_users_info" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "UpdatedDate" timestamp with time zone NOT NULL, "Country" varchar(255) NULL, "Phone" varchar(20) NULL, "Follower" integer NOT NULL, "Following" integer NOT NULL, "userid_id" integer NOT NULL);
--
-- Create model FollowData
--
CREATE TABLE "AddUser_followdata" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "FollowId_id" integer NOT NULL, "FollowerId_id" integer NOT NULL);
ALTER TABLE "AddUser_users_info" ADD CONSTRAINT "AddUser_users_info_userid_id_e180c12a_fk_auth_user_id" FOREIGN KEY ("userid_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "AddUser_users_info_userid_id_e180c12a" ON "AddUser_users_info" ("userid_id");
ALTER TABLE "AddUser_followdata" ADD CONSTRAINT "AddUser_followdata_FollowId_id_49459319_fk_auth_user_id" FOREIGN KEY ("FollowId_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "AddUser_followdata" ADD CONSTRAINT "AddUser_followdata_FollowerId_id_38d4f0ca_fk_auth_user_id" FOREIGN KEY ("FollowerId_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "AddUser_followdata_FollowId_id_49459319" ON "AddUser_followdata" ("FollowId_id");
CREATE INDEX "AddUser_followdata_FollowerId_id_38d4f0ca" ON "AddUser_followdata" ("FollowerId_id");
COMMIT;
