# Generated by Django 4.1.3 on 2023-04-08 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
                ('Country', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=20, null=True, verbose_name='Contact Phone')),
                ('Follower', models.IntegerField(default=0)),
                ('Following', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FollowId', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='User2Follow', to=settings.AUTH_USER_MODEL)),
                ('FollowerId', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='User2Follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
