# Generated by Django 4.1.3 on 2023-02-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FollowerId', models.IntegerField(default=0)),
                ('FollowingID', models.IntegerField(default=0)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
                ('FirstName', models.CharField(default='FirstName', max_length=255)),
                ('LastName', models.CharField(default='LastName', max_length=255, null=True)),
                ('Country', models.CharField(max_length=255, null=True)),
                ('Follower', models.IntegerField(default=0)),
                ('Following', models.IntegerField(default=0)),
            ],
        ),
    ]
