# Generated by Django 4.1.3 on 2023-03-08 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AddUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
                ('Country', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=20, null=True, verbose_name='Contact Phone')),
                ('Follower', models.IntegerField(default=0)),
                ('Following', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='followdata',
            name='FollowerId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followingdata',
            name='FollowingID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
