# Generated by Django 4.1.3 on 2023-04-09 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AddUser', '0002_followdata_createddate_followdata_updateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followdata',
            name='FollowId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='FollowId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followdata',
            name='FollowerId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='FpllowerId', to=settings.AUTH_USER_MODEL),
        ),
    ]
