# Generated by Django 4.1.3 on 2023-04-09 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AddUser', '0003_alter_followdata_followid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followdata',
            name='FollowId',
        ),
        migrations.RemoveField(
            model_name='followdata',
            name='FollowerId',
        ),
        migrations.AddField(
            model_name='followdata',
            name='FollowId',
            field=models.ManyToManyField(blank=True, default=1, related_name='FollowId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followdata',
            name='FollowerId',
            field=models.ManyToManyField(blank=True, default=1, related_name='FpllowerId', to=settings.AUTH_USER_MODEL),
        ),
    ]
