# Generated by Django 4.1.3 on 2023-04-11 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('AddUser', '0005_alter_followdata_followerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_info',
            old_name='Follower',
            new_name='FollowerCount',
        ),
        migrations.RenameField(
            model_name='users_info',
            old_name='Following',
            new_name='FollowingCount',
        ),
    ]
