# Generated by Django 4.1.3 on 2023-04-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AddUser', '0006_rename_follower_users_info_followercount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followdata',
            name='FollowId',
        ),
        migrations.RemoveField(
            model_name='followdata',
            name='FollowerId',
        ),
        migrations.AddField(
            model_name='followdata',
            name='FollowId',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='followdata',
            name='FollowerId',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
