# Generated by Django 4.1.3 on 2023-06-27 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('AddUser', '0008_followdata_followersid_followdata_followsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followdata',
            name='FollowsID',
        ),
    ]
