# Generated by Django 4.1.3 on 2023-06-28 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AddUser', '0009_remove_followdata_followsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='followdata',
            name='FollowsId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_info',
            name='FollowersId',
            field=models.ManyToManyField(related_name='AllFollowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
