# Generated by Django 4.2.1 on 2023-06-29 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AddUser', '0013_rename_userid_users_info_userid_followdata_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followdata',
            name='UserId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
