# Generated by Django 4.2.1 on 2023-06-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddUser', '0014_alter_followdata_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followdata',
            name='FollowersId',
        ),
        migrations.AlterField(
            model_name='followdata',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='followdata',
            name='FollowersId',
            field=models.IntegerField(default=0),
        ),
    ]
