# Generated by Django 4.1.3 on 2023-07-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AddUser', '0015_remove_followdata_followersid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followdata',
            name='FollowersId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='followdata',
            name='UserId',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
