# Generated by Django 4.1.3 on 2023-07-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AddUser', '0017_users_info_active_users_info_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='PrivateAccount',
            field=models.BooleanField(default=False),
        ),
    ]
