# Generated by Django 4.1.3 on 2023-07-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AddUser', '0018_users_info_privateaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='ProfilePic',
            field=models.ImageField(default=None, null=True, upload_to='ProfilePic'),
        ),
    ]
